### ISSUE TITLE
trying out try.wq.io: data entry, usability, models

### ISSUE THREAD

**Issue by managingwholes** [powered-by-wq/try.wq.io#15]
Hi Andrew:

Experimenting now with data entry, and experiencing some chafe with the data model and vera. It will be a common situation for us to enter data the day or week after it was observed. When I try to submit an observation with a date other than today's date, it is overwritten. (I have no problem with datestamping submissions, but to expose this field to the user misleadingly suggests that they can change it.) Do I therefore have to include another date field in my campaign? When the report sits in my Outbox and then I click on it (many users may want to review their submissions before syncing), the lat and lon disappear, along with the location picker, and resubmission leads to an error  (because lat and lon are missing?).

I am now wondering about simplifying the data model, a simpler model without ReportStatus or vera but with campaigns with parameters as addable rows. Would you have a models.py that would work with this, and could I keep most of the app and just drop the db and start over, or would more extensive changes be required?

thanks

**Comment by sheppard** [comment]
Note that there are two dates in the model - `Event.date` (i.e. the date when the observation occurred) and `Report.entered` (i.e. the date when the record entered the system).  The editable field in the submission form refers to the event date rather than the report date (which is automatically assigned upon submission).  So, it does make sense to have it be editable, though this could certainly be made clearer in the interface.  For example, the report_detail view could be updated to show both dates: 

``` html
<tr>
  <td>Observed On</td><td>{{#event}}{{date}}{{/event}}</td>
</tr>
<tr>
  <td>Reported On</td><td>{{entered_label}}</td>
</tr>
```

(Currently the observation date does show up, but only in the link to the Event detail view).

The location edit issue is a bug - see #16.

If you'd like to get rid of the Event/Report distinction, the simplest path forward would probably be to add some new models in phases, keeping the existing models around until you get everything working.
1. Create a new `Observation` model:
   - This can be a direct subclass of `models.Model`
   - Define it in `campaigns/models.py`, recreating whichever fields from the `Report` and `Event` models you find useful.
   - Register with the router in rest.py (`rest.router.register_model(Observation)`).
   - Copy `report_edit.html` to `observation_edit.html` (and similarly for `_list` and `_detail`).  Replace all references to Report/reports with Observation/observations.  Also shorten any event-related references since those will all be fields directly on the Observation model (e.g. `event[date]` will become just `date`). 
   - Similarly, create a copy of `trywq/reports.js` as `trywq/observations.js`, replace any field references in the file, and register it in `trywq/main.js`.
   - Once this is done, you should be able to test by adding a link to `/observations` to your index.html.  The form should be working but won't have any EAV fields.
2. Create a new `ObservationValue` model.
   - This will replicate vera's [Result](https://github.com/wq/vera/blob/master/vera/models.py#L193-L198) model.
   - You can point the "type" `ForeignKey` at the existing `Parameter` model, which will stay (though in a modified form).
   - Create custom serializer classes in `campaigns/serializers.py`.  The purpose of the classes are to enable the necessary server logic to process multiple `ObservationValue` instances attached to an `Observation` when you submit it.  You should be able to use [ResultSerializer](https://github.com/wq/vera/blob/master/vera/serializers.py#L21-L34) as a reference for `ObservationValueSerializer`, and [ReportSerializer](https://github.com/wq/vera/blob/master/vera/serializers.py#L45-L47) as a reference for `ObservationSerializer`.
   - Update your model registration in rest.py to use the new serializer classes:
     
     ``` python
     rest.router.register_model(
         Observation,
         serializer=ObservationSerializer,
         has_values=True, # Flag for wq/app.js
     )
     rest.router.register_model(
         ObservationValue,
         serializer=ObservationValueSerializer,
     )
     
     rest.router.set_extra_config(
         # ...
         attachmentTypes={
             # ...
             'result': {
                 'predicate': 'has_values',
                 'type': 'parameter',
                 # See trywq/config.js for other settings
             }
         }
     )
     ```
3. Make `Parameter` model independent from vera
   - Replicate the three fields from [BaseParameter](https://github.com/wq/vera/blob/master/vera/models.py#L156-L159) on your `Parameter` class, and make it a direct subclass of `patterns.IdentifiedRelatedModel` rather than of `vera.BaseParameter`.
   - Search through your code and remove all remaining references to `vera` (grep is useful for this), including the `Event` and `Report` model registrations.
   - Back up (if desired), destroy, and recreate your Postgres database - it will be easier than trying to explain to Django what happened to all of the models.

**Comment by sheppard** [comment]
I started some new documentation on how to create custom EAV patterns:
https://wq.io/docs/nested-forms
