### ISSUE TITLE
Social Auth urls not catching

### ISSUE THREAD

**Issue by joshglenn** [powered-by-wq/try.wq.io#3]
When I try to access the login part of the website, and I choose, let's say, Github to login. When I click the link, I get a django 404 error page saying it couldn't find the static file. What do I need to do to get the social auth working?

**Comment by sheppard** [comment]
You'll need to request OAuth credentials from each of the providers and configure them - e.g. see http://psa.matiasaguirre.net/docs/backends/github.html.  I usually put these in `local_settings.py` which is why they aren't present in the checked in code.  (Eventually I'll create a `local_settings.py.template` with placeholders for each value.)

**Comment by joshglenn** [comment]
Oh. Okay. Makes perfect sense. Thank you.
